apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
# Uncomment type: NodePort & nodePort: <port> to expose mongo to internet.
  type: NodePort
  ports:
  - name: "9743"
    nodePort: 30083
    port: 9743
    targetPort: 9743
  selector:
    app: order